name: gql_websocket_link
description: GQL Graphql over Websocket Link
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  meta: ^1.3.0
  rxdart: ^0.26.0
  uuid: ^3.0.1
  freezed_annotation:
  #firebase_database: ^8.0.0
  #firebase_core:
#   path: ^1.8.0

dev_dependencies:
  gql_pedantic: ^1.0.2
  test: ^1.16.0
  build_runner:
  freezed:
